# docker-compose.yml
version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"      # HTTP API
      - "6334:6334"      # gRPC API (optional)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__LOG_LEVEL=info

volumes:
  qdrant_storage:
